services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: devdocker-compose -f docker-compose.prod.yml up
    ports:
      - "8080:8080"
    volumes:
      - .:/src/ChatConnectAPI  # Mount local source code for hot reload
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  chathub:
    build:
      context: .
      dockerfile: ./ChatHub/Dockerfile
    ports:
      - "7192:7192"
    volumes:
      - ./ChatHub:/app/ChatHub  # Mount local source code for hot reload
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
