services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev # Use the dev stage for hot reload
    ports:
      - "8080:8080"
    volumes:
      - .:/src/ChatConnectAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
    depends_on: 
      - db
  chathub:
    build:
      context: .
      dockerfile: ./ChatHub/Dockerfile
    ports:
      - "7192:7192"
    volumes:
      - .:/app/publish
    depends_on:
      - db      
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"